testId: dd28e57d-36de-4157-a465-d7e4c2c7300c
testPlan: url-test.json
testType: URL
engineInstances: 1
splitAllCSVs: False
displayName: load-test-demo-001
description: demo用の簡単なテスト
autoStop:
  errorPercentage: 90
  timeWindow: 60
  maximumVirtualUsersPerEngine: 5000
referenceIdentities:
- kind: KeyVault
  type: SystemAssigned
- kind: Metrics
  type: SystemAssigned
