name: load-testing-demo

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  load-testing-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Load Testing Demo
        uses: azure/load-testing@v1
          with:
            loadTestConfigFile: 'config.yaml'
            loadTestResource: 'lt-app-testing-demo'
            resourceGroup: 'rg-app-testing-demo'
      
      - name: Upload Load Test Results
        uses: actions/upload-artifact@v3
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/loadTest
